
'use client'

import type { Metadata } from 'next'
import '../styles/index.scss'
import '@fontsource/inter/400.css'
import '@fontsource/inter/500.css'
import '@fontsource/inter/600.css'
import '@fontsource/inter/700.css'
import {type ReactNode, useState} from 'react'

import { store } from '@/shared/store'
import { Provider } from 'react-redux'
import {Header, type Language} from '@/widgets/Header'

//todo fix metadata
const metadata: Metadata = {

  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  const [language, setLanguage] = useState<Language>('EN')
  return (
    <Provider store={store}>
      <html lang="en">
        <body>
          <Header selectedLanguage={language} onLanguageChange={setLanguage}/>
          {children}
        </body>
      </html>
    </Provider>
  )
}
